version: 2

project_name: dragon

builds:
  - id: dragon
    main: ./cmd/dragon
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

archives:
  - formats: ['tar.gz']
    ids: [dragon]

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github

release:
  github:
    owner: getDragon-dev
    name: dragon-cli
  draft: false
  prerelease: false